### ISSUE TITLE
Upd README.md to include the annotation and label required for a secret to sync

### ISSUE THREAD

**Issue by joaocc** [flanksource/vcluster-sync-host-secrets#5]
Hi,
After looking at the code, it seems that the following are required for a secret to be synchronized to vcluster.
It would be helpful that the example given in README.md includes these.
```
  labels:
    plugin.vcluster.loft.sh/managed-by: host-secret-syncer
  annotations:
    com.flanksource/vcluster-sync: 'true'
```
it would also be useful to provide example of how to customize the target namespace inside vcluster:
```
    plugin: 
      sync-host-secrets:
        image: docker.io/flanksource/vcluster-sync-host-secrets:v0.1.4
        env:
          - name: DESTINATION_NAMESPACE
            value: dest-ns-inside-vcluster
```
Thanks
